spring:

  profiles:
    include: jwt #jwt.yml 불러오기
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  devtools:
    restart:
      enabled: false
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
server:
  servlet:
    session:
      timeout: 1800