spring:

  jackson:
    serialization:
      fail-on-empty-beans: false

  profiles:
    include: jwt, aws #jwt.yml 불러오기
  h2:
    console:
      enabled: true



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  devtools:
    restart:
      enabled: false

  datasource:
    url: jdbc:mysql://pickpickdb.cyvzvqw3b97a.ap-northeast-2.rds.amazonaws.com:3306/test
    username: root
    password: pickpick




logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
server:
  servlet:
    session:
      timeout: 1800


file:
  dir: C:\Users\dh101\Desktop\pickpick\