spring:
  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        # show formatted sql
        format_sql: true
        show_sql: true
server:
  servlet:
    session:
      timeout: 1800